Sdk 390 generate nonce
dfinity/agent-js pull request #554
Opened 2022-04-06 22:48 UTC by krpeacock

# Description

HttpAgent will now provide a unique nonce in calls to ensure that the replica treats each call as unique.

# How Has This Been Tested?

Tested in our integration test suie

# Checklist:

- [ ] My changes follow the guidelines in [CONTRIBUTING.md](https://github.com/dfinity/agent-js/blob/main/CONTRIBUTING.md).
- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2022-04-06 23:12 UTC, ericswanson-dfinity requested changes
There is at least one place that is still calling  `<agent>.addTransform(makeNonceTransform())`: https://github.com/dfinity/agent-js/blob/main/demos/ledgerhq/src/main.js#L86

and a few that add a different nonce transform, but without specifying the `disableNonce` option.
Examples:
- https://github.com/dfinity/agent-js/blob/main/packages/agent/src/agent/http/http.test.ts#L52
- https://github.com/dfinity/agent-js/blob/main/packages/agent/src/actor.test.ts#L102

2022-04-06 23:12 UTC, ericswanson-dfinity commented on docs/generated/changelog.html
> +          during the agent initalization.
Can we say something about removing existing calls to `  agent.addTransform(makeNonceTransform());` ? 

```suggestion
          during the agent initialization.
```

2022-04-06 23:20 UTC, krpeacock commented
> There is at least one place that is still calling `<agent>.addTransform(makeNonceTransform())`: https://github.com/dfinity/agent-js/blob/main/demos/ledgerhq/src/main.js#L86
> 
> and a few that add a different nonce transform, but without specifying the `disableNonce` option. Examples:
> 
> * https://github.com/dfinity/agent-js/blob/main/packages/agent/src/agent/http/http.test.ts#L52
> * https://github.com/dfinity/agent-js/blob/main/packages/agent/src/actor.test.ts#L102

Updated the changelog with upgrade instructions!

2022-04-07 17:27 UTC, ericswanson-dfinity approved these changes

2022-04-07 17:27 UTC, merged