feat: add AssetManager
dfinity/agent-js pull request #603
Opened 2022-07-28 00:10 UTC by sea-snake

# Description

Currently there's the AssetManager implementation available [here](https://www.npmjs.com/package/@slide-computer/assets).

This PR improves on this implementation and moves it to @dfinity/assets.

The AssetManager has list, store, delete, get, batch and clear methods to manage assets in an asset storage canister.

Fixes #602

# How Has This Been Tested?

- `AssetManager` has e2e tests (browser)
- `ReadableData` has unit tests

# Checklist:

- [ ] My changes follow the guidelines in [CONTRIBUTING.md](https://github.com/dfinity/agent-js/blob/main/CONTRIBUTING.md).
- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2022-07-28 00:14 UTC, sea-snake commented
PR is work in progress.

Main points that are still TODO:
- Implement a way to track events and/or progress
- Additional unit and e2e tests
- Documentation
- Example application

2022-09-27 00:06 UTC, sea-snake commented
Example application PR: https://github.com/dfinity/examples/pull/355

2022-09-27 18:38 UTC, krpeacock requested changes

2022-09-27 18:38 UTC, krpeacock commented on packages/assets/src/index.ts
> +    const fd = await new Promise<number>(async (resolve, reject) =>
This will need to be refactored for the lint check

2022-09-27 18:38 UTC, krpeacock commented on packages/assets/src/index.ts
> +              // @ts-ignore
we prefer `as unknown as <expected-type>` when the TS engine can't pick up on an expected type

2022-09-27 18:38 UTC, krpeacock commented on packages/assets/tsconfig.json
> +    "allowJs": false,
if you do choose to make the IDL a JS file, you'll need to set this to true

2022-09-27 18:40 UTC, krpeacock commented
This is close to ready, and the main logic looks solid! To manually run the lint checks, you can run `npm run lint --workspace @dfinity/assets`

2022-09-29 00:33 UTC, sea-snake commented
> This is close to ready, and the main logic looks solid! To manually run the lint checks, you can run `npm run lint --workspace @dfinity/assets`

Thanks for the helpful feedback! I've resolved these points in the latest commit.

2022-09-29 18:02 UTC, krpeacock approved these changes

2022-10-04 06:40 UTC, domwoe commented
@sea-snake Seems there is still an issue with the timeout for the E2E tests.

2022-10-04 22:25 UTC, sea-snake commented
> @sea-snake Seems there is still an issue with the timeout for the E2E tests.

Ended up reducing the asset size in the tests (e.g. from 1MB to 1KB) to decrease the test duration. On a local environment, the speed in more in line with expectation (2s) for each chunk but it seems things take a bit longer on the automated test env.

2022-10-05 09:47 UTC, domwoe commented
Thanks @sea-snake!
@krpeacock Seems to be ready to be merged now.

2022-10-05 20:02 UTC, krpeacock commented
@sea-snake is it concerning that the tests were timing out with a minute to run for a 3mb upload?

2022-10-05 22:56 UTC, sea-snake commented
@krpeacock 
I've benchmarked all steps involved. Some observations I've made:
- Sha256 in JS is slow, sadly the current native web implementation doesn't allow incremental hashing so it's not an alternative (You don't want to load a big file in memory if avoidable).
- Every update call takes approx. 2s. For a 3MB asset test there are 5 calls (create_batch, create_chunk, create_chunk, commit_batch and delete_asset). If all these calls were made sequentially, this would be 10s. The create_chunk calls are made in parallel in theory but the dfx environment (local, production, system it's running on) might make a difference there.
- The psuedo random bytes generator in the test isn't the fastest code out there but didn't seem to make a big influence on the overall test duration.
- Maybe the cbor encoding of the update call messages might also affect the speed depending on the system it's running on.

2022-10-05 23:03 UTC, sea-snake commented
@krpeacock 
One difference between node and web is that fetch in node is still using http1.1 instead of http2 if I remember correctly. Might be interesting to see if there's a difference in performance when tests are run in cypress.

2022-10-05 23:25 UTC, krpeacock commented
I'll go ahead and merge so we can get this work in front of people, and I'll create an issue to follow up on automating some benchmarks

2022-10-05 23:25 UTC, sea-snake commented
Doing some more debugging now to see if there are some other issues slowing things down.

2022-10-05 23:26 UTC, merged