feat: allow passing `DBCreateOptions` to `IdbStorage` constructor
dfinity/agent-js pull request #850
Opened 2024-02-19 11:28 UTC by hpeebles

# Description

Each `IdbStorage` instance wraps an `IdbKeyVal` instance which itself can be configured via the `DBCreateOptions`.
Prior to this PR there are no configuration options when creating `IdbStorage` instances.
This PR makes it such that `IdbStorage` instances can optionally be configured by passing `DBCreateOptions` in the constructor which will feed through to the inner `IdbKeyVal`.

# How Has This Been Tested?

It has only been tested via the automated tests.

# Checklist:

- [ ] My changes follow the guidelines in [CONTRIBUTING.md](https://github.com/dfinity/agent-js/blob/main/CONTRIBUTING.md).
- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2024-02-21 19:08 UTC, krpeacock requested changes
Suggestions:
- prefer [private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) over typescript `private` keyword
- JSDocs for constructor

2024-02-21 19:08 UTC, krpeacock commented on packages/auth-client/src/storage.ts
> +  constructor(private options?: DBCreateOptions) {
```suggestion
  #options: DBCreateOptions;

  /**
   * @param options - DBCreateOptions
   * @param options.dbName - name for the indexeddb database
   * @param options.storeName - name for the indexeddb Data Store
   * @param options.version - version of the database. Increment to safely upgrade
   * @constructs an {@link IdbStorage}
   * @example
   * ```typescript
   * const storage = new IdbStorage({ dbName: 'my-db', storeName: 'my-store', version: 2 });
   * ```
   */
  constructor(options?: DBCreateOptions) {
    this.#options = options ?? {};
```

2024-02-21 19:08 UTC, krpeacock commented on packages/auth-client/src/storage.ts
> +      IdbKeyVal.create(this.options).then(db => {
```suggestion
      IdbKeyVal.create(this.#options).then(db => {
```

2024-02-22 14:50 UTC, hpeebles commented
> Suggestions:
> 
> * prefer [private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) over typescript `private` keyword
> * JSDocs for constructor

Nice! I'd never come across these before. I've merged in your suggestions.

2024-03-18 23:26 UTC, krpeacock approved these changes

2024-03-19 17:15 UTC, merged